/**
 * Engine — reads CONFIG, loads components, renders & animates.
 * DO NOT edit this file for customization. Edit config.js only.
 */

// ── Theme ────────────────────────────────────────────────────────
let currentMode = (CONFIG.defaultMode || "dark");

function applyTheme(mode) {
  currentMode = mode;
  const root = document.documentElement;
  const c = CONFIG.colors;

  root.style.setProperty("--primary", c.primary || "#ff69b4");
  root.style.setProperty("--accent", c.accent || "#15a1ed");

  const theme = c[mode] || c.dark || {};
  root.style.setProperty("--bg", theme.background || "#1a1a2e");
  root.style.setProperty("--text", theme.text || "#ffffff");
  root.style.setProperty("--surface", mode === "dark" ? "rgba(250, 243, 224, 0.08)" : "rgba(43, 45, 66, 0.06)");
  root.style.setProperty("--surface-strong", mode === "dark" ? "rgba(250, 243, 224, 0.14)" : "rgba(43, 45, 66, 0.10)");
  root.style.setProperty("--ink-line", mode === "dark" ? "rgba(212, 163, 115, 0.22)" : "rgba(201, 24, 74, 0.16)");

  // Update toggle icon
  const btn = document.getElementById("theme-toggle");
  if (btn) btn.textContent = mode === "dark" ? "☀️" : "🌙";
}

function createThemeToggle() {
  const btn = document.createElement("button");
  btn.id = "theme-toggle";
  btn.title = "Toggle dark/light mode";
  btn.textContent = currentMode === "dark" ? "☀️" : "🌙";
  btn.addEventListener("click", () => {
    applyTheme(currentMode === "dark" ? "light" : "dark");
  });
  document.body.appendChild(btn);
}

// ── Script Loader ────────────────────────────────────────────────
function loadScript(src) {
  return new Promise((resolve, reject) => {
    const s = document.createElement("script");
    s.src = src;
    s.onload = resolve;
    s.onerror = () => reject(new Error("Component not found: " + src));
    document.head.appendChild(s);
  });
}

// ── Main ─────────────────────────────────────────────────────────
document.addEventListener("DOMContentLoaded", async () => {
  applyTheme(currentMode);
  createThemeToggle();

  // Set music source
  const audio = document.querySelector(".song");
  if (audio && CONFIG.music) {
    const source = audio.querySelector("source");
    if (source) {
      source.src = CONFIG.music;
      // Handle standard audio types
      if (CONFIG.music.toLowerCase().endsWith(".mpeg") || CONFIG.music.toLowerCase().endsWith(".mp3")) {
        source.type = "audio/mpeg";
      } else if (CONFIG.music.toLowerCase().endsWith(".wav")) {
        source.type = "audio/wav";
      } else if (CONFIG.music.toLowerCase().endsWith(".ogg")) {
        source.type = "audio/ogg";
      }
    }
    audio.load();
  }

  // Determine unique component types
  const types = [...new Set(CONFIG.sections.map((s) => s.type))];

  // Dynamically load component scripts
  for (const type of types) {
    try {
      await loadScript(`./script/components/${type}.js`);
    } catch (e) {
      console.warn(e.message);
    }
  }

  // Render all sections
  const container = document.querySelector(".container");
  const rendered = [];

  CONFIG.sections.forEach((section) => {
    const comp = window.Components && window.Components[section.type];
    if (!comp) {
      console.warn(`Component "${section.type}" not found, skipping.`);
      return;
    }
    const el = comp.render(container, section, CONFIG);
    rendered.push({ el, comp, section });
  });

  // SweetAlert music prompt.
  const isDark = currentMode === "dark";
  Swal.fire({
    title: `For ${CONFIG.name}`,
    text: "Open your birthday surprise from Team Growziq.",
    showCancelButton: true,
    confirmButtonColor: CONFIG.colors.primary || "#D4A373",
    cancelButtonColor: "#6f6a66",
    confirmButtonText: "Open with music",
    cancelButtonText: "View quietly",
    background: isDark ? "#211722" : "#ffffff",
    color: isDark ? "#FAF3E0" : "#2B2D42",
  }).then((result) => {
    document.querySelectorAll(".swal2-container").forEach((el) => el.remove());

    if (result.isConfirmed && audio) {
      audio.volume = 0;
      audio.play().catch(() => {});
      // Smooth fade-in
      let vol = 0;
      const fadeIn = setInterval(() => {
        vol = Math.min(vol + 0.05, 1);
        audio.volume = vol;
        if (vol >= 1) clearInterval(fadeIn);
      }, 100);
    }
    buildTimeline(rendered);
  });
});

// ── Skip Button ───────────────────────────────────────────────────
function createSkipButton(getTl) {
  const btn = document.createElement("button");
  btn.id = "skip-btn";
  btn.textContent = "Tap to Skip >";
  btn.setAttribute("aria-label", "Skip current section");
  document.body.appendChild(btn);

  btn.addEventListener("click", () => {
    const tl = getTl();
    if (!tl) return;
    if (tl.paused()) {
      // Resume from a pause point (candle / gift)
      tl.play();
    } else {
      // Skip ahead in auto-playing sections
      tl.seek(tl.time() + 3, false);
    }
  });
}

// ── Timeline Builder ─────────────────────────────────────────────
function buildTimeline(rendered) {
  const tl = gsap.timeline({
    onComplete: () => {
      const btn = document.getElementById("skip-btn");
      if (btn) btn.style.opacity = "0";
    },
  });

  // Give skip button access to the timeline
  createSkipButton(() => tl);

  tl.to(".container", { duration: 0.6, visibility: "visible" });

  // Track deferred exits for overlay components
  let deferredExits = [];

  rendered.forEach(({ el, comp, section }, i) => {
    const isOverlay = comp.overlay === true;

    // Flush deferred exits before non-overlay sections
    if (!isOverlay && deferredExits.length > 0) {
      deferredExits.forEach((fn) => fn());
      deferredExits = [];
    }

    // Hide skip button when reaching candle section (and all sections after it)
    if (section.type === "candle") {
      tl.to("#skip-btn", { duration: 0.5, opacity: 0, pointerEvents: "none" });
    }

    // Animate
    comp.animate(tl, el, CONFIG);

    // Show bunting banner specifically after balloons section starts
    if (section.type === "balloons") {
      tl.call(() => {
        const bunting = document.getElementById("bunting");
        if (bunting) bunting.classList.add("is-visible");
      });
    }

    // Handle exit lifecycle
    if (comp.exit) {
      const next = rendered[i + 1];
      const nextIsOverlay = next && next.comp.overlay === true;

      if (nextIsOverlay) {
        deferredExits.push(() => comp.exit(tl, el));
      } else if (!isOverlay) {
        comp.exit(tl, el);
      }
    }
  });

  // Flush remaining
  deferredExits.forEach((fn) => fn());

  // Setup replay
  const replayBtn = document.getElementById("replay");
  if (replayBtn) {
    replayBtn.addEventListener("click", () => tl.restart());
  }
}
